In [10]:
#ANALISIS DE PLATAFORMAS Y STORES


from get_rawg_platforms_df import fetch_platforms_df
import pandas as pd

pd.set_option("display.max_rows", None)
#from get_rawg_stores_df import fetch_stores_df

import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("RAWG_API_KEY")

platforms_df = fetch_platforms_df(API_KEY)
#stores_df = fetch_stores_df(API_KEY)

platforms_df = platforms_df.sort_values(by="games_count", ascending=False)
#stores_df.head()

,platform_id,platform_name,platform_slug,games_count,image_background
0,4,PC,pc,560716,https://media.rawg.io/media/games/587/587588c6...
50,171,Web,web,260067,https://media.rawg.io/media/games/8ba/8ba1178d...
11,5,macOS,macos,108040,https://media.rawg.io/media/games/7fa/7fa0b586...
12,6,Linux,linux,80386,https://media.rawg.io/media/games/49c/49c3dfa4...
6,3,iOS,ios,77443,https://media.rawg.io/media/games/238/2383a172...
7,21,Android,android,52528,https://media.rawg.io/media/games/b4e/b4e4c73d...
3,18,PlayStation 4,playstation4,6988,https://media.rawg.io/media/games/b45/b45575f3...
5,7,Nintendo Switch,nintendo-switch,5768,https://media.rawg.io/media/games/fc1/fc1307a2...
2,1,Xbox One,xbox-one,5739,https://media.rawg.io/media/games/511/5118aff5...
15,16,PlayStation 3,playstation3,3203,https://media.rawg.io/media/games/4a0/4a0a1316...
16,15,PlayStation 2,playstation2,2869,https://media.rawg.io/media/games/459/459ac874...
13,14,Xbox 360,xbox360,2829,https://media.rawg.io/media/games/d1a/d1a2e99a...
9,9,Nintendo DS,nintendo-ds,2501,https://media.rawg.io/media/screenshots/590/59...
21,11,Wii,wii,2231,https://media.rawg.io/media/screenshots/157/15...
31,166,Commodore / Amiga,commodore-amiga,2084,https://media.rawg.io/media/screenshots/101/10...
17,27,PlayStation,playstation1,1693,https://media.rawg.io/media/games/2ae/2aedae90...
8,8,Nintendo 3DS,nintendo-3ds,1682,https://media.rawg.io/media/games/041/04102601...
1,187,PlayStation 5,playstation5,1464,https://media.rawg.io/media/games/20a/20aa03a1...
18,19,PS Vita,ps-vita,1461,https://media.rawg.io/media/games/fd7/fd794a9f...
19,17,PSP,psp,1443,https://media.rawg.io/media/screenshots/601/60...
4,186,Xbox Series S/X,xbox-series-x,1242,https://media.rawg.io/media/games/5f6/5f61441e...
20,10,Wii U,wii-u,1114,https://media.rawg.io/media/games/cc1/cc196a5a...
28,49,NES,nes,1025,https://media.rawg.io/media/screenshots/656/65...
27,79,SNES,snes,991,https://media.rawg.io/media/screenshots/52b/52...
24,24,Game Boy Advance,game-boy-advance,964,https://media.rawg.io/media/games/087/08727beb...
14,80,Xbox,xbox-old,868,https://media.rawg.io/media/games/9d4/9d45e22d...
40,167,Genesis,genesis,850,https://media.rawg.io/media/screenshots/f7a/f7...
37,34,Atari ST,atari-st,836,https://media.rawg.io/media/games/e6a/e6a509fe...
29,55,Classic Macintosh,macintosh,674,https://media.rawg.io/media/games/38a/38af9694...
22,105,GameCube,gamecube,662,https://media.rawg.io/media/games/9d4/9d45e22d...
26,26,Game Boy,game-boy,617,https://media.rawg.io/media/games/057/0573c1c9...
25,43,Game Boy Color,game-boy-color,429,https://media.rawg.io/media/games/7ca/7ca0df41...
30,41,Apple II,apple-ii,424,https://media.rawg.io/media/games/941/94139518...
41,107,SEGA Saturn,sega-saturn,378,https://media.rawg.io/media/games/44f/44f1fd0d...
45,106,Dreamcast,dreamcast,374,https://media.rawg.io/media/games/743/7430f184...
23,83,Nintendo 64,nintendo-64,363,https://media.rawg.io/media/screenshots/61f/61...
36,25,Atari 8-bit,atari-8-bit,309,https://media.rawg.io/media/games/876/8764efc5...
34,23,Atari 2600,atari-2600,294,https://media.rawg.io/media/screenshots/ff6/ff...
44,74,SEGA Master System,sega-master-system,239,https://media.rawg.io/media/screenshots/347/34...
48,77,Game Gear,game-gear,229,https://media.rawg.io/media/games/687/687c7ac9...
42,119,SEGA CD,sega-cd,163,https://media.rawg.io/media/screenshots/9a0/9a...
49,12,Neo Geo,neogeo,126,https://media.rawg.io/media/screenshots/f1b/f1...
46,111,3DO,3do,101,https://media.rawg.io/media/games/47b/47b50d88...
33,31,Atari 5200,atari-5200,64,https://media.rawg.io/media/screenshots/678/67...
32,28,Atari 7800,atari-7800,64,https://media.rawg.io/media/screenshots/565/56...
38,46,Atari Lynx,atari-lynx,57,https://media.rawg.io/media/screenshots/d71/d7...
43,117,SEGA 32X,sega-32x,46,https://media.rawg.io/media/screenshots/d9f/d9...
47,112,Jaguar,jaguar,40,https://media.rawg.io/media/games/8fc/8fcc2ff5...
10,13,Nintendo DSi,nintendo-dsi,37,https://media.rawg.io/media/screenshots/078/07...
35,22,Atari Flashback,atari-flashback,30,https://media.rawg.io/media/screenshots/2aa/2a...
39,50,Atari XEGS,atari-xegs,22,https://media.rawg.io/media/screenshots/769/76...

In [11]:

import pandas as pd

pd.set_option("display.max_rows", None)
from get_rawg_stores_df import fetch_stores_df

import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("RAWG_API_KEY")


stores_df = fetch_stores_df(API_KEY)

stores_df = stores_df.sort_values(by="games_count", ascending=False)

stores_df

,store_id,store_name,store_slug,games_count,domain,image_background
8,9,itch.io,itch,654200,itch.io,https://media.rawg.io/media/games/e63/e635b8c7...
0,1,Steam,steam,123332,store.steampowered.com,https://media.rawg.io/media/games/120/1201a40e...
3,4,App Store,apple-appstore,75590,apps.apple.com,https://media.rawg.io/media/games/13a/13a528ac...
7,8,Google Play,google-play,17126,play.google.com,https://media.rawg.io/media/games/9fa/9fa63622...
5,6,Nintendo Store,nintendo,9151,nintendo.com,https://media.rawg.io/media/games/d2c/d2c74dac...
1,3,PlayStation Store,playstation-store,8076,store.playstation.com,https://media.rawg.io/media/games/736/73619bd3...
4,5,GOG,gog,7244,gog.com,https://media.rawg.io/media/games/587/587588c6...
2,2,Xbox Store,xbox-store,4938,microsoft.com,https://media.rawg.io/media/games/34b/34b1f185...
6,7,Xbox 360 Store,xbox360,1915,marketplace.xbox.com,https://media.rawg.io/media/games/bc0/bc06a29c...
9,11,Epic Games,epic-games,1451,epicgames.com,https://media.rawg.io/media/games/1bd/1bd2657b...